name: Hugo Build & Deploy

on:
  push:
    branches:
      - master   # or master depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # 3. Build the Hugo site
      - name: Build Hugo Site
        run: hugo --minify

      # 4. Install Netlify CLI
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # 5. Deploy to Netlify
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID}}
        run: netlify deploy --dir=public --prod --site $NETLIFY_SITE_ID
